"""position 테이블에서 부서명 컬럼 제거

Revision ID: 52ca960a5f75
Revises: 54ad29016f85
Create Date: 2026-04-28 11:37:40.211900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


revision: str = "52ca960a5f75"
down_revision: Union[str, Sequence[str], None] = "54ad29016f85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    cols = {c["name"] for c in inspect(conn).get_columns("positions")}
    if "department_name" not in cols:
        return
    op.drop_column("positions", "department_name")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "positions",
        sa.Column(
            "department_name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="부서명",
        ),
    )
    # ### end Alembic commands ###
